LojaYgor3/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LojaYgor3.Models
{
    public class Cliente
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Nome { get; set; }
        [EmailAddress(ErrorMessage = "Digite um email válido")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório")]
        public string CPF { get; set; }
    }
}

LojaYgor3/Models/LojaContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace LojaYgor3.Models
{
    public class LojaContext : DbContext
    {
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Produto> Produtos { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Produto>().HasRequired(produto => produto.Cliente);
        }
    }
}

LojaYgor3/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LojaYgor3.Models
{
    public class Produto
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
        public string Nome { get; set; }
        public decimal Preco { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
        public DateTime Data { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
        public int ClienteId { get; set; }
        public Cliente Cliente { get; set; }
    }
}

LojaYgor3/Controllers/ClienteController.cs
using LojaYgor3.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaYgor3.Controllers
{
    public class ClienteController : Controller
    {
        LojaContext contexto = new LojaContext();
        
        // GET: Cliente
        public ActionResult Index()
        {
            return View(contexto.Clientes.ToList());
        }

        // GET: Cliente/Details/5
        public ActionResult Detalha(int id)
        {
            return GetCliente(id);
        }        

        // GET: Cliente/Create
        public ActionResult Adiciona()
        {
            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        public ActionResult Adiciona(Cliente cliente)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    contexto.Clientes.Add(cliente);
                    contexto.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Edit/5
        public ActionResult Atualiza(int id)
        {
            return GetCliente(id);
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        public ActionResult Atualiza(int id, Cliente cliente)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    contexto.Entry(cliente).State = EntityState.Modified;
                    contexto.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View();
                
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Delete/5
        public ActionResult Remove(int id)
        {
            return GetCliente(id);
        }

        // POST: Cliente/Delete/5
        [HttpPost]
        public ActionResult Remove(int id, Cliente cliente)
        {
            try
            {
                // TODO: Add delete logic here
                cliente = contexto.Clientes.Find(id);
                contexto.Clientes.Remove(cliente);
                contexto.SaveChanges();
                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }

        private ActionResult GetCliente(int id)
        {
            var cliente = (from c in contexto.Clientes
                           where c.Id == id
                           select c).First();
            return View(cliente);
        }
    }
}

LojaYgor3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaYgor3.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

LojaYgor3/Controllers/ProdutoController.cs
using LojaYgor3.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaYgor3.Controllers
{
    public class ProdutoController : Controller
    {
        LojaContext contexto = new LojaContext();

        // GET: Produto
        public ActionResult Index()
        {
            var produtos = contexto.Produtos.Include(produto => produto.Cliente);
            return View(produtos.ToList());
        }

        // GET: Produto/Details/5
        public ActionResult Detalha(int id)
        {
            return GetProduto(id);
        }

        private ActionResult GetProduto(int id)
        {
            var produto = (from p in contexto.Produtos.Include(p => p.Cliente)
                           where p.Id == id
                           select p).First();
            return View(produto);
        }

        // GET: Produto/Create
        public ActionResult Adiciona()
        {
            ViewBag.ClienteId = new SelectList(contexto.Clientes, "Id", "Nome");
            return View();
        }

        // POST: Produto/Create
        [HttpPost]
        public ActionResult Adiciona(Produto produto)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    contexto.Produtos.Add(produto);
                    contexto.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ClienteId = new SelectList(contexto.Clientes, "Id", "Nome", produto.ClienteId);
                return View(produto);
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Edit/5
        public ActionResult Atualiza(int id)
        {
            return GetProdutoPorId(id);
        }


        // POST: Produto/Edit/5
        [HttpPost]
        public ActionResult Atualiza(int id, Produto produto)
        {
            try
            {
                // TODO: Add update logic here
                contexto.Entry(produto).State = EntityState.Modified;
                contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Delete/5
        public ActionResult Remove(int id)
        {
            return GetProdutoPorId(id);
        }

        // POST: Produto/Delete/5
        [HttpPost]
        public ActionResult Remove(int id, Produto produto)
        {
            try
            {
                // TODO: Add delete logic here
                produto = contexto.Produtos.Find(id);
                contexto.Produtos.Remove(produto);
                contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private ActionResult GetProdutoPorId(int id)
        {
            var produto = (from p in contexto.Produtos.Include(p => p.Cliente)
                           where p.Id == id
                           select p).First();
            ViewBag.ClienteId = new SelectList(contexto.Clientes, "Id", "Nome", produto.ClienteId);
            return View(produto);
        }
    }
}

LojaYgor3/Views/Cliente/Adiciona.cshtml
@model LojaYgor3.Models.Cliente

@{
    ViewBag.Title = "Adiciona";
}

<h2>Novo Cliente</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

LojaYgor3/Views/Cliente/Atualiza.cshtml
@model LojaYgor3.Models.Cliente

@{
    ViewBag.Title = "Atualizar";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

LojaYgor3/Views/Cliente/Detalha.cshtml
@model LojaYgor3.Models.Cliente

@{
    ViewBag.Title = "Detalhes";
}

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Nome</dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>E-Mail</dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>CPF</dt>

        <dd>
            @Html.DisplayFor(model => model.CPF)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Atualiza", new { id = Model.Id }) |
    @Html.ActionLink("Voltar", "Index")
</p>

LojaYgor3/Views/Cliente/Index.cshtml
@model IEnumerable<LojaYgor3.Models.Cliente>

@{
    ViewBag.Title = "Clientes";
}

<h2>Clientes</h2>

<p>
    @Html.ActionLink("Novo Cliente", "Adiciona")
</p>
<table class="table table-hover">
    <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>CPF</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CPF)
        </td>
        <td>
            @Html.ActionLink("Editar", "Atualiza", new { id=item.Id }) |
            @Html.ActionLink("Detalhes", "Detalha", new { id=item.Id }) |
            @Html.ActionLink("Remover", "Remove", new { id=item.Id })
        </td>
    </tr>
}

</table>

LojaYgor3/Views/Cliente/Remove.cshtml
@model LojaYgor3.Models.Cliente

@{
    ViewBag.Title = "Remover";
}
<h3>Tem certeza que deseja remover?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Nome</dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>E-Mail</dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>CPF</dt>

        <dd>
            @Html.DisplayFor(model => model.CPF)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-danger" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

LojaYgor3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Início";
}

<h2>Bem vindo à Loja</h2>

LojaYgor3/Views/Produto/Adiciona.cshtml
@model LojaYgor3.Models.Produto

@{
    ViewBag.Title = "Novo Produto";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteId, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClienteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

LojaYgor3/Views/Produto/Atualiza.cshtml
@model LojaYgor3.Models.Produto

@{
    ViewBag.Title = "Atualizar";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteId, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClienteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

LojaYgor3/Views/Produto/Detalha.cshtml
@model LojaYgor3.Models.Produto

@{
    ViewBag.Title = "Detalhes";
}
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Nome</dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>Preço</dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>Data do Pedido</dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt>Cliente</dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nome)
        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Atualiza", new { id = Model.Id }) |
    @Html.ActionLink("Voltar", "Index")
</p>

LojaYgor3/Views/Produto/Index.cshtml
@model IEnumerable<LojaYgor3.Models.Produto>

@{
    ViewBag.Title = "Produtos";
}

<h2>Produtos</h2>

<p>
    @Html.ActionLink("Novo Produto", "Adiciona")
</p>
<table class="table table-hover">
    <tr>
        <th>Nome</th>
        <th>Preço</th>
        <th>Data do Pedido</th>
        <th>Cliente</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.Nome)
        </td>
        <td>
            @Html.ActionLink("Editar", "Atualiza", new { id=item.Id }) |
            @Html.ActionLink("Detalhes", "Detalha", new { id=item.Id }) |
            @Html.ActionLink("Remover", "Remove", new { id=item.Id })
        </td>
    </tr>
}

</table>

LojaYgor3/Views/Produto/Remove.cshtml
@model LojaYgor3.Models.Produto

@{
    ViewBag.Title = "Remover";
}
<h3>Tem certeza que deseja remover?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Nome</dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>Preço</dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>Data do Pedido</dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt>Cliente</dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nome)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-danger" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

LojaYgor3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LojaYgor</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    @Html.Partial("_MenuSuperior")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ygor Vieira</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

LojaYgor3/Views/Shared/_MenuSuperior.cshtml
<nav>
    <div class="container-fluid">
        <ul class="nav nav-tabs">
            <li>@Html.ActionLink("Início", "Index", "Home")</li>
            <li>@Html.ActionLink("Produtos", "Index", "Produto")</li>
            <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
        </ul>
    </div>
</nav>